import config from "config";
import jwt from "jsonwebtoken";
import express from "express";
import {
  authHeader,
  jwtSecretConfigLabel
} from "../../src/constants/constants";

/**
 * Middleware function that verifies the authentication token
 * from the header to make sure it was generated by our secret.
 */
export default function auth(
  req: express.Request,
  res: express.Response,
  next: express.NextFunction
) {
  //check for token
  const token = req.header(authHeader);
  if (!token) {
    return res.status(401).json({ msg: "Authorization denied" });
  }
  try {
    //verify token
    const decoded = jwt.verify(token, config.get(jwtSecretConfigLabel));
    //Add user from payloag.
    (req as any).jwtDecod = decoded;
    next();
  } catch (e) {
    return res.status(400).json({ msg: "Invalid token" });
  }
}
